#!/usr/bin/env python3
"""Regenerate `preset_shapes.xml` from the upstream ECMA-376 preset definitions.

The upstream file is `presetShapeDefinitions.xml` — the DrawingML preset shape
table from ECMA-376 Part 1 §20.1.9.18 (ST_ShapeType), as redistributed by the
Apache POI project under the Apache License 2.0:

    https://raw.githubusercontent.com/apache/poi/trunk/poi/src/main/resources/\
org/apache/poi/sl/draw/geom/presetShapeDefinitions.xml

Two transformations are applied, both lossless with respect to what
`shape_geometry` reads:

1. **Shape of the document.** Upstream keys each preset by *element name*
    (`<accentBorderCallout1>…`), which a static schema cannot deserialize
    without 187 named fields. Each becomes `<sp n="accentBorderCallout1">`, so
    the table is one `Vec<PresetEntry>`.

2. **Dropped subtrees.** `ahLst` (adjust handles — the UI drag affordances) and
    `cxnLst` (connection sites — where a connector may attach) are removed.
    Neither is read by `build_geometry`; together they are ~55% of the bytes.
    `avLst`, `gdLst`, `rect` and `pathLst` are kept verbatim, minus the
    redundant per-element `xmlns` declaration and inter-tag whitespace.

Usage:

    curl -sSLo /tmp/presetShapeDefinitions.xml <url above>
    python3 crates/liteparse-ooxml/assets/minify_presets.py \
        /tmp/presetShapeDefinitions.xml crates/liteparse-ooxml/assets/preset_shapes.xml
"""

import re
import sys

HEADER = """<!-- DrawingML preset shape definitions (ECMA-376 Part 1 §20.1.9.18).
     Derived from presetShapeDefinitions.xml as redistributed by Apache POI
     under the Apache License 2.0; see ../ATTRIBUTION.md.
     Generated by assets/minify_presets.py — do not edit by hand. -->
"""


def minify(src: str) -> str:
    presets = re.split(r"\n  <([A-Za-z0-9]+)>\n", src)
    out = [HEADER, "<presetShapes>"]
    count = 0
    for i in range(1, len(presets), 2):
        name, body = presets[i], presets[i + 1]
        body = body.split(f"</{name}>")[0]
        # Drop the subtrees nothing reads.
        body = re.sub(r"<ahLst\b.*?</ahLst>", "", body, flags=re.S)
        body = re.sub(r"<cxnLst\b.*?</cxnLst>", "", body, flags=re.S)
        body = re.sub(r"<ahLst\b[^>]*/>|<cxnLst\b[^>]*/>", "", body)
        # Drop the per-element default-namespace declaration: quick-xml matches
        # on the local name, and every element here is in the `a:` namespace.
        body = re.sub(r'\s+xmlns="[^"]*"', "", body)
        # Collapse inter-tag whitespace. No element here has text content, so
        # this cannot eat data.
        body = re.sub(r">\s+<", "><", body).strip()
        out.append(f'<sp n="{name}">{body}</sp>')
        count += 1
    out.append("</presetShapes>\n")
    print(f"{count} presets", file=sys.stderr)
    return "\n".join(out)


if __name__ == "__main__":
    with open(sys.argv[1], encoding="utf-8") as fh:
        result = minify(fh.read())
    with open(sys.argv[2], "w", encoding="utf-8") as fh:
        fh.write(result)
